### PR TITLE
[RFC] Monitor dbus ops

### PR DESCRIPTION
**Pull request by hectorj2f**
This PR doesn't intend to be merged, just to verify we're in the same page.

@htr

### CODE REVIEW

**Comment by htr** [comment]
yes, something in those lines.

**Comment by htr** [comment]
@hectorj2f  this might be useful: https://github.com/giantswarm/fleet/blob/v0.11.3-gs-2/udplogger/udplogger.go

```
socat udp-recv:4444 STDOUT | tee log
```

for example

**Comment by hectorj2f** [comment]
@htr I'll test it today :P

**Comment by hectorj2f** [comment]
Related to https://github.com/giantswarm/giantswarm/issues/368

**Comment by hectorj2f** [comment]
We don't need it anymore

**Pull request closed without merging**
