### PR TITLE
Bug hunting, tests fixing, add new tests, govet and gofmt

### PR DESCRIPTION
**Pull request by hectorj2f**
- [x] Fix existing tests
- [x] Fix error with the version
- [x] Rename capability `!ENGINE!` to `DISABLE_ENGINE` which is related to `Disable_engine` flag.
- [x] Remove Identify function from rpc registry
- [x] Add new unit tests for the new functionalities
- [x] gofmt, govet

Related to : https://github.com/giantswarm/giantswarm/issues/481

### CODE REVIEW

**Comment by htr** [comment]
we should revert `fec7206` in this branch

**Comment by hectorj2f** [comment]
@htr `no-block flag to false` this changes was to my branch which was outdated in comparison with `htr-grpc-registry`. As you can see, there isn't any change related to this in the PR

**Comment by hectorj2f** [comment]
@htr okay, so we wanted to 'true' ack :+1:

**Comment by hectorj2f** [comment]
ping @htr, I added all the tests we can do in this first iteration. I believe those are good enough to send the PR, although we could be asked to add more specific ones :/.

**Pull request merged**
