### PR TITLE
WIP: CPU performance improvements

### PR DESCRIPTION
**Pull request by hectorj2f**
- [ ] Use `ffjson` instead of golang `encoding/json` package. Reference links: https://journal.paul.querna.org/articles/2014/03/31/ffjson-faster-json-in-go/
- [ ] ...
- [ ] ..

### CODE REVIEW

**Comment by zeisss** [comment]
I think you need merge into another branch. @htr wanted to keep master as it is upstream.

**Comment by hectorj2f** [comment]
Thanks! @ZeissS I'll do so whenever I get some progress. Which branch btw ?

**Comment by zeisss** [comment]
Hugos stuff seems to be in `gs-2`, so your branch should be based on that and merge there. I guess. Maybe @htr Can chum in here .

**Comment by hectorj2f** [comment]
Moving to gs-2 :/

**Pull request closed without merging**
